name: sales_forecasting
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pandas>=1.3.0
  - numpy>=1.21.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - jupyter
  - notebook
  - ipykernel
  - openpyxl
  - pytorch
  - tensorflow
  - tqdm
  - pip
  - pip:
    - statsmodels>=0.12.0
    - pathlib2>=2.3.6
